apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: demo-helm
  namespace: instavote
spec:
  interval: 1m0s
  url: https://iamsureshgithub.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-helm-staging-011
  namespace: instavote
spec:
  chart:
    spec:
      chart: demo-helm
      sourceRef:
        kind: HelmRepository
        name: demo-helm
      version: 0.1.*
  interval: 10m0s
  #releaseName: demo-helm-staging-011
  #targetNamespace: demohelm-nginx
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled