---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2024-09-03T08:24:51.138764265Z"
  name: instavote
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/iamsureshgithub/instavote.git
