---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote
  namespace: instavote
spec:
  interval: 30s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/iamsureshgithub/instavote_deploy.git
